# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# It's not necessary to copy all keys to your config.
# If the key is missing in your config, "default-config.toml" will serve as a fallback

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
  #'exec-and-forget sketchybar >> $HOME/.sketchybar/service.log 2>&1',
  # JankyBorders has a built-in detection of already running process,
  # so it won't be run twice on AeroSpace restart
  'exec-and-forget pkill -f borders',
  'exec-and-forget brew services restart borders'
]
# Notify Sketchybar about workspace change
#exec-on-workspace-change = [
#  '/bin/bash',
#  '-c',
#  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE FOCUSED_DISPLAY=$(aerospace list-monitors --focused | awk "{print $1}")',
#]

# Notify Sketchybar about focuse change
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
on-focus-changed = [
  #'exec-and-forget sketchybar --trigger aerospace_focus_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 0

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
#on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 7
inner.vertical = 7
outer.left = 7
outer.bottom = 0
outer.top = [
  { monitor."LG HDR 4K" = 0 },
  #{ monitor."Sidecar Display" = 0 },
  0,
]
outer.right = 7

# Define my fancy key notation
# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right
#New in 0.18
#     "pageUp": .pageUp,
#    "pageDown": .pageDown,
#    "home": .home,
#    "end": .end,
#   "forwardDelete": .forwardDelete,

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# You can uncomment this line to open up terminal with alt + enter shortcut
# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
alt-enter = 'exec-and-forget open -a finder'


# See: https://nikitabobko.github.io/AeroSpace/goodness#open-a-new-window-with-applescript

cmd-h = []     # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"
alt-f = 'fullscreen'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
# See: https://nikitabobko.github.io/AeroSpace/commands#focus
cmd-alt-comma = 'focus left'
cmd-alt-period = 'focus right'
alt-down = 'focus down'
alt-up = 'focus up'
alt-right = 'focus right'
# See: https://nikitabobko.github.io/AeroSpace/commands#move
# alt-shift-left = 'move left'
# alt-shift-down = 'move down'
# alt-shift-up = 'move up'
# alt-shift-right = 'move right'
alt-shift-left = 'join-with left'
alt-shift-down = 'join-with down'
alt-shift-up = 'join-with up'
alt-shift-right = 'join-with right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'
alt-shift-c = 'reload-config'

#Scrolling through workspaces
cmd-ctrl-alt-shift-leftSquareBracket = 'workspace prev'
cmd-ctrl-alt-shift-rightSquareBracket = 'workspace next'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace Browsers'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 0'
cmd-ctrl-alt-g = 'workspace Games'
cmd-ctrl-alt-b = 'workspace Browsers'
cmd-ctrl-alt-n = 'workspace Notes'
cmd-ctrl-alt-t = 'workspace Trash'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace Browsers'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 0'
cmd-ctrl-alt-shift-g = 'move-node-to-workspace Games'
cmd-ctrl-alt-shift-n = 'move-node-to-workspace Notes'
cmd-ctrl-alt-shift-t = 'move-node-to-workspace Trash'


# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
#alt-tab = 'workspace-back-and-forth'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = [
  'mode service',
  'exec-and-forget sketchybar --trigger aerospace_enter_service_mode',
]
#Custom
alt-t = [
  'layout floating tiling'
]

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = [
  'reload-config',
  'mode main',
  #'exec-and-forget sketchybar --trigger aerospace_leave_service_mode',
]
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = [
  #'layout floating tiling',
  #'mode main',
  #'exec-and-forget sketchybar --trigger aerospace_leave_service_mode',
] # Toggle between floating and tiling layout
backspace = [
  #'close-all-windows-but-current',
  'mode main',
  #'exec-and-forget sketchybar --trigger aerospace_leave_service_mode',
]

alt-shift-left = [
  'join-with left',
  'mode main',
  #'exec-and-forget sketchybar --trigger aerospace_leave_service_mode',
]
alt-shift-down = [
  'join-with down',
  'mode main',
  #'exec-and-forget sketchybar --trigger aerospace_leave_service_mode',
]
alt-shift-up = [
  'join-with up',
  'mode main',
  #'exec-and-forget sketchybar --trigger aerospace_leave_service_mode',
]
alt-shift-right = [
  'join-with right',
  'mode main',
  #'exec-and-forget sketchybar --trigger aerospace_leave_service_mode',
]

#[[on-window-detected]]
#run = ['layout floating']
[[on-window-detected]]
if.app-id = 'com.apple.Terminal'
run = ['layout tiling','layout v_tiles','move-node-to-workspace 0']

[[on-window-detected]]
if.app-id = 'com.raphaelamorim.rio'
run = ['layout tiling','layout v_tiles','move-node-to-workspace 0']

[[on-window-detected]]
if.app-name-regex-substring = '^wezterm-gui$'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'org.chromium.Chromium'
run = ['layout accordion','fullscreen','move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'YYR4'
run = ['layout accordion','move-node-to-workspace Trash','macos-native-minimize']

#If it's the Main Frame of CSP, Lock it in
[[on-window-detected]]
if.app-id = 'jp.co.celsys.CLIPSTUDIOPAINT'
if.window-title-regex-substring = 'MainFrame'
run = ['layout accordion','fullscreen','move-node-to-workspace 2']

#If it's the stupid clip studio sub frames, make them float
[[on-window-detected]]
if.app-id = 'jp.co.celsys.CLIPSTUDIOPAINT'
if.window-title-regex-substring = ''
run = ['layout floating','move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'com.unity3d.unityhub'
run = ['layout floating', 'move-node-to-workspace 7']

[[on-window-detected]]
if.app-id = 'com.unity3d.UnityEditor5.x'
run = ['layout floating', 'move-node-to-workspace 7']

[[on-window-detected]]
if.app-id = 'pureref.app-id'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.Photos'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.finder'
if.workspace = '0'
run = ['layout tiling']

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = ['layout tiling', 'move-node-to-workspace 0']

[[on-window-detected]]
if.app-id = 'com.vscodium'
run = ['layout tiles horizontal vertical', 'move-node-to-workspace 0']

[[on-window-detected]]
if.app-id = 'com.jetbrains.rider'
run = 'move-node-to-workspace 0'

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = 'move-node-to-workspace 0'

[[on-window-detected]]
if.app-id = 'org.blenderfoundation.blender'
run = ['layout floating','fullscreen', 'move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'org.blenderfoundation.blender'
if.window-title-regex-substring = 'Blender File View'
run = ['layout floating', 'move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'org.blenderfoundation.blender'
if.window-title-regex-substring = 'Image Editor'
run = ['layout floating', 'move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'org.blenderfoundation.blender'
if.window-title-regex-substring = 'Blender Render'
run = ['layout floating', 'move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'com.ef.EcoFlow'
run = ['layout floating', 'move-node-to-workspace 0']

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
if.workspace = '2'
run = ['layout tiling vertical','move-node-to-workspace Browsers']

[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = ['layout tiling vertical','move-node-to-workspace Browsers']

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = ['move-node-to-workspace Browsers']

[[on-window-detected]]
if.app-id = 'com.netease.163music'
run = ['move-node-to-workspace 6']

[[on-window-detected]]
if.app-id = 'com.electron.vutronmusic'
run = ['move-node-to-workspace 6']

[[on-window-detected]]
if.app-id = 'com.electron.yesplaymusic'
run = ['move-node-to-workspace 6']

[[on-window-detected]]
if.app-id = 'Nightshade'
run = ['move-node-to-workspace 7']

[[on-window-detected]]
if.app-id = 'Glaze'
run = ['move-node-to-workspace 7']
